# Generated by Django 5.0.6 on 2024-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=17982),
        ),
    ]
