# Generated by Django 5.0.6 on 2024-07-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='org_id',
            new_name='orgId',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=35740),
        ),
    ]
